learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views


app_name = 'basic_app'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views


urlpatterns = [
    path('',  views.index, name="index"),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render


def index(request):
    context_dict = {'text': 'Hello World', 'number': 100}
    return render(request, 'basic_app/index.html', context_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BASE</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">"
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top" >
      <div class="container">
          <ul class="nav navbar-nav">
           <li class="nav navbar-brand"><a href="{% url 'index' %}#">HOME</a></li>
           <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
           <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
          </ul>
      </div>
    </nav>
    <div class="container">
        {% block body_block %}
      <!-- para herdar tudo fora disto -->
        {% endblock %}
    </div>
 </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
   {% extends "basic_app/base.html" %}
   {% block  body_block %}
   <h1>Welcome to HOME</h1>
     <h2>Exemplo de herança template</h2>
      <h1>{{ text|cut:'World' }}</h1
      <h1>{{ number|add:"99" }}</h1>
    {%  endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
   {% extends "basic_app/base.html" %}
   {% block  body_block %}
   <h1>Welcome to OTHER</h1>
     <h2>Exemplo de herança template</h2>
    {%  endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>RELATIVE</title>
</head>
<body>
      <h1>Welcome to RELATIVE URL TEMPLATES</h1>
     <a href="{% url 'basic_app:other' %}">The OTHER PAGE</a></p>
     <a href="{% url 'admin:index' %}">Administrator</a>
</body>
</html>